name: CI
on: [ push, pull_request ]
jobs:
  Build:
    name: Build image and push SNAPSHOT from main
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Lint Connector Runtime Dockerfile
      uses: hadolint/hadolint-action@v2.0.0
      with:
        dockerfile: runtime/Dockerfile

    - name: Lint Connector Bundle Dockerfile
      uses: hadolint/hadolint-action@v2.0.0
      with:
        dockerfile: bundle/bash/Dockerfile

    - name: Lint Connector Bundle Dockerfile
      uses: hadolint/hadolint-action@v2.0.0
      with:
        dockerfile: bundle/mvn/camunda-saas-bundle/Dockerfile

    - name: Lint Connector Bundle Dockerfile
      uses: hadolint/hadolint-action@v2.0.0
      with:
        dockerfile: bundle/mvn/default-bundle/Dockerfile

    - name: Import Secrets
      id: secrets
      uses: hashicorp/vault-action@v2.4.2
      with:
        url: ${{ secrets.VAULT_ADDR }}
        method: approle
        roleId: ${{ secrets.VAULT_ROLE_ID }}
        secretId: ${{ secrets.VAULT_SECRET_ID }}
        exportEnv: false # we rely on step outputs, no need for environment variables
        secrets: |
          secret/data/products/connectors/ci/common DOCKERHUB_USER;
          secret/data/products/connectors/ci/common DOCKERHUB_PASSWORD;
          secret/data/products/connectors/ci/common ARTIFACTORY_USR;
          secret/data/products/connectors/ci/common ARTIFACTORY_PSW;

    - name: Setup Java Build
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
        server-id: camunda-nexus
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: Deploy default-bundle Maven Artifact
      run: mvn -B compile generate-sources source:jar javadoc:jar deploy
      if: github.ref == 'refs/heads/main'
      working-directory: bundle/mvn/default-bundle/
      env:
        MAVEN_USERNAME: ${{ steps.secrets.outputs.ARTIFACTORY_USR }}
        MAVEN_PASSWORD: ${{ steps.secrets.outputs.ARTIFACTORY_PSW }}

    - name: Deploy saas-bundle Maven Artifact
      run: mvn -B compile generate-sources source:jar javadoc:jar deploy
      if: github.ref == 'refs/heads/main'
      working-directory: bundle/mvn/camunda-saas-bundle/
      env:
        MAVEN_USERNAME: ${{ steps.secrets.outputs.ARTIFACTORY_USR }}
        MAVEN_PASSWORD: ${{ steps.secrets.outputs.ARTIFACTORY_PSW }}

    - name: Build default-bundle Maven Artifact
      run: mvn -B compile install
      if: github.ref != 'refs/heads/main'
      working-directory: bundle/mvn/default-bundle/
      env:
        MAVEN_USERNAME: ${{ steps.secrets.outputs.ARTIFACTORY_USR }}
        MAVEN_PASSWORD: ${{ steps.secrets.outputs.ARTIFACTORY_PSW }}

    - name: Build saas-bundle Maven Artifact
      run: mvn -B compile install
      if: github.ref != 'refs/heads/main'
      working-directory: bundle/mvn/camunda-saas-bundle/
      env:
        MAVEN_USERNAME: ${{ steps.secrets.outputs.ARTIFACTORY_USR }}
        MAVEN_PASSWORD: ${{ steps.secrets.outputs.ARTIFACTORY_PSW }}


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      if: github.ref == 'refs/heads/main'
      with:
        username: ${{ steps.secrets.outputs.DOCKERHUB_USER }}
        password: ${{ steps.secrets.outputs.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker Image tag SNAPSHOT - Runtime
      uses: docker/build-push-action@v3
      with:
        context: runtime/
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: camunda/connectors:SNAPSHOT

    - name: Build and Push Docker Image tag SNAPSHOT - bundle-bash
      uses: docker/build-push-action@v3
      with:
        context: bundle/bash/
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: camunda/connectors-bundle-bash:SNAPSHOT

    - name: Build and Push Docker Image tag SNAPSHOT - bundle-default
      uses: docker/build-push-action@v3
      with:
        context: bundle/mvn/default-bundle/
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: camunda/connectors-bundle:SNAPSHOT

    - name: Build and Push Docker Image tag SNAPSHOT - bundle-saas
      uses: docker/build-push-action@v3
      with:
        context: bundle/mvn/camunda-saas-bundle/
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: camunda/connectors-bundle-saas:SNAPSHOT
